-- Disable RLS on data tables (only users/profiles need RLS for auth)
ALTER TABLE scholars DISABLE ROW LEVEL SECURITY;
ALTER TABLE topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE content DISABLE ROW LEVEL SECURITY;
ALTER TABLE books DISABLE ROW LEVEL SECURITY;
ALTER TABLE audiobooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE watchlist DISABLE ROW LEVEL SECURITY;
ALTER TABLE gatherings DISABLE ROW LEVEL SECURITY;
ALTER TABLE gathering_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_preferences DISABLE ROW LEVEL SECURITY;
